### ISSUE TITLE
setup.py depends on pypandoc before having a chance to install it.

### ISSUE THREAD

**Issue by JulienPalard** [ptrus/suffix-trees#8]
So we just can't install suffix-trees:

```
Collecting suffix-trees (from deploy-client==0.0.1)
  Downloading suffix-trees-0.2.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-793aivvt/suffix-trees/setup.py", line 3, in <module>
        import pypandoc
    ModuleNotFoundError: No module named 'pypandoc'

```

**Comment by JulienPalard** [comment]
Oh I see you're converting from markdown to rst for pypi, have you tried https://packaging.python.org/specifications/core-metadata/#description-content-type-optional?
